# Generated by Django 3.1 on 2020-08-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timtTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('semister', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('p1', models.CharField(max_length=50)),
                ('p2', models.CharField(max_length=50)),
                ('p3', models.CharField(max_length=50)),
                ('p4', models.CharField(max_length=50)),
                ('p5', models.CharField(max_length=50)),
                ('p6', models.CharField(max_length=50)),
                ('p7', models.CharField(max_length=50)),
                ('p8', models.CharField(max_length=50)),
                ('time1', models.TimeField()),
                ('time2', models.TimeField()),
                ('time3', models.TimeField()),
                ('time4', models.TimeField()),
                ('time5', models.TimeField()),
                ('time6', models.TimeField()),
                ('time7', models.TimeField()),
                ('time8', models.TimeField()),
                ('studentsDetails_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.studentsdetails')),
            ],
        ),
    ]
