# Generated by Django 3.1 on 2020-08-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timttable',
            name='studentsDetails_id',
        ),
    ]
