# Generated by Django 3.1 on 2020-08-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('time_table', '0002_remove_timttable_studentsdetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timttable',
            name='studentsDetails_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.studentsdetails'),
        ),
    ]
