# Generated by Django 3.1 on 2020-08-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='student_id',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
