# Generated by Django 3.1 on 2020-08-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_attendence_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='p6',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='p7',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='p8',
        ),
        migrations.AddField(
            model_name='attendence',
            name='abs_no',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='attendence',
            name='abs_prcentage',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='attendence',
            name='pre_no',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='attendence',
            name='pre_prcentage',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
