# Generated by Django 3.1 on 2020-08-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Roll_no', models.CharField(max_length=50)),
                ('mail_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=500)),
                ('Branch', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('semister', models.CharField(max_length=50)),
                ('dob', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='OK', max_length=200)),
            ],
        ),
    ]
